### ISSUE TITLE
Deprecate and recommend Tokio instead

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [kennytm/async-ctrlc#5]
- [Tokio does the same thing](https://docs.rs/tokio/latest/tokio/signal/fn.ctrl_c.html)
- There's no need for two functions that do the same thing to be maintained
- The Tokio one is going to be maintained anyways
- So this one does not need to be maintained
- So why not recommend people to use Tokio instead of this one?

**Comment by kennytm** [comment]
> * So why not recommend people to use Tokio instead of this one?

because [Rust has more than one async runtime](https://rust-lang.github.io/async-book/08_ecosystem/00_chapter.html#popular-async-runtimes).

**Comment by ChocolateLoverRaj** [comment]
I Will try the Tokio function with the `futures` executor and see if it works

**Comment by ChocolateLoverRaj** [comment]
You're right, the Tokio function only works with Tokio so Tokio cannot always be a replacement for this library.
